CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100),
    first_name varchar(100),
    last_name varchar(100),
    CONSTRAINT uc_User_Login UNIQUE (login)
);

